name: Publish Plugin
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CHAIN_CRT: ${{ secrets.CHAIN_CRT }}
      INTELLIJ_TOKEN: ${{ secrets.INTELLIJ_TOKEN }}
      PEM_PASSWORD: ${{ secrets.PEM_PASSWORD }}
      PRIVATE_PEM: ${{ secrets.PRIVATE_PEM }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
      - name: Java Version
        run: java -version
      - name: Gradle Version
        run: gradle -version
      - name: Gradle Build
        run: gradle test
      - name: Build
        run: gradle buildPlugin
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build/distributions/*.zip